name: delpick_admin
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.5.1 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  web: ^1.1.1
  webview_flutter: ^4.10.0

  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  animated_toggle_switch: ^0.8.4
  cached_network_image: ^3.4.1
  image_picker_web: ^3.1.1
  clipboard: ^0.1.3
  cloud_firestore: ^5.6.5
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  data_table_2: ^2.6.0
  dio: ^5.8.0+1
  dynamic_path_url_strategy:
  fl_chart: ^0.70.2
  flutter_dotenv: ^5.2.1
  flutter_dropzone:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^9.2.4
  flutter_typeahead: ^5.2.0
  file_picker: ^10.0.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  firebase_storage: ^12.4.4
  get: ^4.7.2
  get_storage: ^2.1.1
  #  get_storage_pro: ^0.1.9
  html: ^0.15.5
  http: ^1.3.0
  iconsax: ^0.0.8
  iconsax_flutter: ^1.0.0
  image_picker: ^1.1.2
#  intl: ^0.20.2
  intl: ^0.19.0
  intl_utils: ^2.8.10
  jwt_decoder: ^2.0.1
  lottie: ^3.3.1
  material_table_view: ^5.1.0
  multiselect_dropdown_flutter: ^0.0.7
  multi_select_flutter: ^4.1.3
  pasteboard: ^0.3.0
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1
#  cupertino_icons: ^1.0.8
  percent_indicator: ^4.0.0
  flutter_charts: ^0.5.2
  provider: ^6.0.1
  font_awesome_flutter: ^10.1.0
  google_fonts: ^4.0.3
  table_calendar: ^3.1.2
  pie_chart: ^5.4.0
#  syncfusion_flutter_calendar: ^28.2.12
  syncfusion_flutter_calendar: ^27.1.50
  responsive_builder: ^0.7.1
#  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
#  flutter_lints: ^4.0.0
  flutter_lints: ^5.0.0
  test: ^1.24.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/icons/payment_methods/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 800

#  # To add assets to your application, add an assets section, like this:
#  assets:
#    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package